dataset:
  name: Motor Vehicle Collisions - Crashes
  base_url: data.cityofnewyork.us
  dataset_id: h9gi-nx95


landing_dir: /Users/carlfinkbeiner/repos/nyc-car-crashes/landing
watermark_path: /Users/carlfinkbeiner/repos/nyc-car-crashes/state/watermark.json
