dataset:
  name: Motor Vehicle Collisions - Crashes
  base_url: data.cityofnewyork.us
  dataset_id: h9gi-nx95
  page_limit: 10


landing_dir: /Users/carlfinkbeiner/repos/nyc-car-crashes/landing
transform_dir: /Users/carlfinkbeiner/repos/nyc-car-crashes/tranform
state_file_path: /Users/carlfinkbeiner/repos/nyc-car-crashes/state/watermark.json

